export class vehicle {
    image?: string
    title?: string
    location?: string
    make?: string
    type?: string
    price?: string
    date?: string
    rating?: string
    model?: string
    year?: string
    transmission?: string
    mileage?: string
    color?: string
    registeredIn?: string
    assembly?: string
    engineCapacity?: string
    lastUpdated?: string
    featuresList?: string
    exteriorCondition?: string
    interiorCondition?: string
    engineCondition?: string
    transmissionCondition?: string
    suspensionCondition?: string
    steeringCondition?: string
    sellerContactNo?: string
    sellerEmail?: string
    sellerLocation?: string
    sellerContactHours?: string
    sellerComments?: string
  }